apiVersion: v1
kind: Service
metadata:
  name: infrara-backend
  namespace: infrara-prod
  labels:
    app: infrara-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: infrara-backend

